services:
  db:
    image: postgres:17.4-bullseye # pin exact patch
    env_file: .env
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-gorm}"]
      interval: 5s
      retries: 5

  api:
    build:
      context: . # looks for Dockerfile here
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["3000:3000"]

volumes:
  pgdata:
